# Generated by Django 4.1 on 2022-08-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='education',
            table='BD_DATABASE_PRESIDENCE"."_education',
        ),
    ]
